---
- name: Install Docker on CentOS 7
  hosts: linuxclient1
  become: True
  become_user: root
  
  tasks:
     - name: Pull
       command: "docker pull magkry/application:1.0"

     - name: Run container
       command: >
         docker run -d
         --name test
         magkry/application:1.0
