---
- name: Install Docker on CentOS 7
  hosts: linuxclient1
  become: True
  become_user: root
  
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
       name: yum-utils
       state: present
        
    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      
    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        
    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Install pip
      yum:
        name: python-pip2
        state: present
    - name: Install Docker Python lib
      pip:
        name: docker
        executable: pip2
        
    - name: log into docker hub registry using the docker_login module
      # community.general.docker_login:
      docker_login:
        username: magkry
        password: Efrei!17Efrei
      # when: dockerhub_login_required | default(true)
      
    - name: Pull image and create the container using docker_container
      # community.general.docker_image:
      docker_image:
        name: magkry/application:1.0
        source: pull
      # when: dockerhub_login_required | default(true)
      
    - name: Start the container using docker_container
      # community.general.docker_container:
      docker_container:  
        name: applicationdep1
        image: magrky/application:1.0
        state: started
        restart_policy: always
