---
- name: Install Docker on CentOS 7
  hosts: linuxclient1
  become: True
  become_user: root
  
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
       name: yum-utils
       state: present
        
    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      
    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        
    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes
   
    - name: Install Python 3
      package:
        name: python3
        state: present
    
    - name: Install Python3 pip
      package:
        name: python3-pip
        state: present
    
    - name: Install Docker Python lib
      pip:
        name: docker
        state: present
        executable: pip3
    
    - name: Ensure Ansible is using correct Python interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      run_once: true
    
    - name: Pull image and create the container using docker_container
      docker_image:
        name: magkry/application:1.0
        source: pull
      
    - name: Start the container using docker_container
      docker_container:  
        name: applicationdep1
        image: magkry/application:1.0
        state: started
        ports:
          - "8080:8080"

     - name: Exit Python interpreter
       command: echo "exit()" | ansible_python_interpreter      
